"""Validation layer — the gate between 'downloaded' and 'about to run installer'."""

from __future__ import annotations

from optionspilot.update.models import Assurance
from optionspilot.update.validation import (
    digest_for, parse_sha256sums, sha256_file, validate,
)

NAME = "OptionsPilot-Setup-v0.5.0.exe"


def _write(tmp_path, data=b"installer-bytes", name=NAME):
    p = tmp_path / name
    p.write_bytes(data)
    return p


class TestParseSha256sums:
    """The manifest parser. Standard `sha256sum` output, defensively read."""

    def test_parses_standard_two_space_format(self):
        digest = "a" * 64
        assert parse_sha256sums(f"{digest}  {NAME}\n") == {NAME: digest}

    def test_parses_binary_mode_star_prefix(self):
        digest = "b" * 64
        assert parse_sha256sums(f"{digest} *{NAME}\n") == {NAME: digest}

    def test_ignores_comments_and_blank_lines(self):
        digest = "c" * 64
        text = f"# generated by CI\n\n{digest}  {NAME}\n\n"
        assert parse_sha256sums(text) == {NAME: digest}

    def test_normalises_digest_case_and_path_prefix(self):
        digest = "D" * 64
        got = parse_sha256sums(f"{digest}  dist/sub\\{NAME}\n")
        assert got == {NAME: "d" * 64}

    def test_unparseable_input_yields_nothing(self):
        """Empty, not an exception — the CALLER decides what absence means,
        and it means different things depending on whether a manifest was
        published at all."""
        assert parse_sha256sums("not a checksum file at all") == {}
        assert parse_sha256sums("") == {}

    def test_digest_for_selects_by_name(self):
        text = f"{'a' * 64}  other.zip\n{'b' * 64}  {NAME}\n"
        assert digest_for(text, NAME) == "b" * 64
        assert digest_for(text, "absent.exe") is None


class TestValidate:
    def test_ok_with_matching_size(self, tmp_path):
        p = _write(tmp_path, b"abc")
        r = validate(p, expected_size=3)
        assert r.ok and not r.failures

    def test_missing_file(self, tmp_path):
        r = validate(tmp_path / "nope.exe", expected_size=10)
        assert not r.ok
        assert "missing" in r.message.lower()

    def test_size_mismatch(self, tmp_path):
        p = _write(tmp_path, b"abc")
        r = validate(p, expected_size=999)
        assert not r.ok
        assert "incomplete" in r.message.lower()

    def test_empty_file_rejected_without_size(self, tmp_path):
        p = _write(tmp_path, b"")
        r = validate(p)                      # no expected size
        assert not r.ok

    def test_bad_name_rejected(self, tmp_path):
        p = _write(tmp_path, b"abc", name="totally-not-setup.exe")
        r = validate(p, expected_size=3)
        assert not r.ok
        assert "installer" in r.message.lower()

    def test_sha256_enforced_when_given(self, tmp_path):
        p = _write(tmp_path, b"abc")
        good = sha256_file(p)
        assert validate(p, expected_size=3, expected_sha256=good).ok
        assert not validate(p, expected_size=3, expected_sha256="deadbeef").ok

    def test_records_all_checks(self, tmp_path):
        p = _write(tmp_path, b"abc")
        r = validate(p, expected_size=3)
        names = {c[0] for c in r.checks}
        assert {"exists", "name", "size"} <= names


def test_sha256_file_matches_hashlib(tmp_path):
    import hashlib
    p = tmp_path / "f.bin"
    p.write_bytes(b"hello world" * 1000)
    assert sha256_file(p) == hashlib.sha256(b"hello world" * 1000).hexdigest()


class TestAssurance:
    """`ok` alone cannot say HOW a file was verified.

    Before V0.9.0-C8 a size-and-name check and a cryptographic check both
    produced `ok=True` and the message "Update verified." — a claim the first
    one had not earned. These tests pin the distinction.
    """

    def test_matching_hash_is_hash_verified(self, tmp_path):
        p = _write(tmp_path, b"abc")
        r = validate(p, expected_size=3, expected_sha256=sha256_file(p))
        assert r.ok
        assert r.assurance is Assurance.HASH_VERIFIED
        assert r.assurance.is_verified
        assert "checksum" in r.message.lower()

    def test_no_published_checksum_is_size_only_and_still_installs(self, tmp_path):
        """The compatibility path for every release made before V0.9.0.

        Failing here would strand existing installations: the client doing the
        checking is the OLD one, and older releases carry no manifest.
        """
        p = _write(tmp_path, b"abc")
        r = validate(p, expected_size=3)
        assert r.ok, "an old release with no manifest must remain installable"
        assert r.assurance is Assurance.SIZE_ONLY
        assert not r.assurance.is_verified
        assert "unavailable" in r.message.lower()

    def test_mismatched_hash_fails_and_is_not_verified(self, tmp_path):
        p = _write(tmp_path, b"abc")
        r = validate(p, expected_size=3, expected_sha256="f" * 64)
        assert not r.ok
        assert r.assurance is Assurance.FAILED
        assert not r.assurance.is_verified
        assert "integrity" in r.message.lower()

    def test_published_manifest_without_our_file_fails(self, tmp_path):
        """Absence of a digest means different things in different contexts.

        No manifest at all is an old release. A manifest that exists and does
        not cover this download is a discrepancy, and it must not install.
        """
        p = _write(tmp_path, b"abc")
        r = validate(p, expected_size=3, checksums_published=True)
        assert not r.ok
        assert r.assurance is Assurance.FAILED
        assert any(name == "sha256_missing" for name, _, _ in r.checks)

    def test_missing_file_is_failed_not_size_only(self, tmp_path):
        r = validate(tmp_path / "nope.exe")
        assert not r.ok and r.assurance is Assurance.FAILED

    def test_hash_comparison_ignores_case_and_surrounding_space(self, tmp_path):
        p = _write(tmp_path, b"abc")
        r = validate(p, expected_size=3,
                     expected_sha256="  " + sha256_file(p).upper() + "\n")
        assert r.ok and r.assurance is Assurance.HASH_VERIFIED
