"""Bundled US symbol directory: ticker validation, autocomplete search, and
bulk-input parsing for the watchlist.

The directory (optionspilot/data_assets/symbols.csv, ~12k NASDAQ/NYSE/AMEX
symbols) is generated by scripts/fetch_symbols.py from the public Nasdaq
Trader listings and shipped with the app, so validation and autocomplete are
instant and offline. Symbols not in the directory aren't necessarily fake —
callers may fall back to a live quote check for the rare unknown-but-real
ticker.
"""

from __future__ import annotations

import csv
import re
import threading
from pathlib import Path

_ASSET = Path(__file__).resolve().parents[1] / "data_assets" / "symbols.csv"
_TOKEN = re.compile(r"[A-Za-z.\-]{1,10}")

_lock = threading.Lock()
_directory: dict[str, str] | None = None


def directory() -> dict[str, str]:
    """{symbol: company name}, loaded once, thread-safe."""
    global _directory
    with _lock:
        if _directory is None:
            with _ASSET.open(newline="", encoding="utf-8") as f:
                reader = csv.reader(f)
                next(reader, None)
                _directory = {row[0]: row[1] for row in reader if len(row) == 2}
        return _directory


def is_known(symbol: str) -> bool:
    return symbol.upper() in directory()


def company_name(symbol: str) -> str:
    return directory().get(symbol.upper(), "")


def search(query: str, limit: int = 8) -> list[dict[str, str]]:
    """Autocomplete: exact symbol first, then symbol prefixes, then name
    substrings — each tier alphabetical."""
    q = query.strip().upper()
    if not q:
        return []
    d = directory()
    exact = [q] if q in d else []
    prefixes = sorted(s for s in d if s.startswith(q) and s != q)
    name_hits = sorted(
        s for s in d
        if not s.startswith(q) and q in d[s].upper()
    ) if len(q) >= 3 else []
    out = []
    for s in (*exact, *prefixes, *name_hits):
        out.append({"symbol": s, "name": d[s]})
        if len(out) >= limit:
            break
    return out


def parse_symbols(raw: str) -> list[str]:
    """Split free-form pasted text (commas / spaces / newlines / semicolons,
    '$AAPL' cashtags, any case) into de-duplicated uppercase tickers,
    input order preserved."""
    seen: set[str] = set()
    out: list[str] = []
    for token in _TOKEN.findall(raw.replace("$", " ")):
        symbol = token.upper().strip(".-")
        if symbol and symbol not in seen:
            seen.add(symbol)
            out.append(symbol)
    return out
